# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-worker/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-worker', Iudex::Worker::VERSION, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.extra_deps += [ [ 'rjack-slf4j',    '~> 1.5.11' ],
                    [ 'rjack-logback',  '>= 0.9.18' ],
                    [ 'gravitext-util', '~> 1.4.0'  ],
                    [ 'iudex-filter',   '~> 1.0.0'  ],
                    [ 'iudex-core',     '~> 1.0.0'  ],
                    [ 'iudex-da',       '~> 1.0.0'  ],
                    [ 'iudex-rome',     '~> 1.0.0'  ],
                    [ 'iudex-httpclient-3', '~> 1.0.0' ] ]

  h.testlib = :minitest
  h.extra_dev_deps += [ [ 'minitest',      '~> 1.5.0'  ] ]

  h.rubyforge_name = "iudex"
end

task :chk_hist_vers do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :chk_init_v do
  t.test_line_match( 'init/iudex-worker', /^gem.+#{t.name}/, /= #{t.version}/ )
end
task :chk_hist_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :chk_hist_vers, :chk_init_v                 ]
task :tag  => [ :chk_hist_vers, :chk_init_v, :chk_hist_date ]
task :push => [                              :chk_hist_date ]

t.define_tasks
