# -*- ruby -*-
#--
# Copyright (C) 2008-2009 David Kellum
#
# Licensed under the Apache License, Version 2.0 (the "License"); you
# may not use this file except in compliance with the License.  You
# may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#++

$LOAD_PATH << './lib'
require 'iudex-da/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.0.0'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-da',
                       Iudex::DA::VERSION,
                       :no_assembly )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.extra_deps += [ [ 'activerecord',          '~> 2.3.4'  ],
                    [ 'jdbc-postgres',         '~> 8.4.701'],
                    [ 'activerecord-jdbcpostgresql-adapter', '~> 0.9.2' ],
                    [ 'rjack-slf4j',           '~> 1.5.8'  ],
                    [ 'rjack-commons-dbcp',    '~> 1.2.2'  ],
                    [ 'rjack-commons-dbutils', '~> 1.3.0'  ],
                    [ 'gravitext-util',        '~> 1.4.0'  ],
                    [ 'iudex-filter',          '~> 1.0.0'  ],
                    [ 'iudex-core',            '~> 1.0.0'  ] ]

  h.rubyforge_name = "iudex"
end

file 'Manifest.txt' => "lib/#{t.name}/base.rb"

t.define_tasks
