# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-da/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-da',
                       Iudex::DA::VERSION,
                       :no_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.extra_deps += [ [ 'iudex-core',            '~> 1.1.0'  ],
                    [ 'activerecord',          '~> 2.3.10' ],
                    [ 'jdbc-postgres',         '>= 8.4.702',  '< 9.1' ],
                    [ 'activerecord-jdbcpostgresql-adapter', '~> 1.1.0' ],
                    [ 'rjack-commons-dbcp',    '~> 1.4.0'  ],
                    [ 'rjack-commons-dbutils', '~> 1.3.0'  ] ]

  h.testlib = :minitest
  h.extra_dev_deps += [ [ 'minitest',          '~> 2.2.0' ],
                        [ 'rjack-logback',     '~> 1.0' ] ]
end

file 'Manifest.txt' => "lib/#{t.name}/base.rb"

task :check_pom_version do
  t.test_line_match( 'pom.xml', /<version>/, /#{t.version}/ )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_version, :check_history_version                      ]
task :tag  => [ :check_pom_version, :check_history_version, :check_history_date ]
task :push => [                                             :check_history_date ]

# Disable verbose warnings, which are a bit much with ActiveRecord
# 2.3.x at least.
Hoe::RUBY_FLAGS.sub!( /\-w(\s|$)/, '-W1\1' )

t.define_tasks
