# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-brutefuzzy-protobuf/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-brutefuzzy-protobuf',
                       Iudex::Brutefuzzy::Protobuf::VERSION,
                       :no_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps   += [ [ 'rjack-protobuf', '~> 2.3.0' ] ]

  h.testlib = :minitest
  h.extra_dev_deps << [ 'minitest',       '>= 1.7.1', '< 2.1' ]
end

directory 'src/main/java'

messages_java = 'src/main/java/iudex/brutefuzzy/protobuf/ProtocolBuffers.java'

file messages_java  => [ 'proto/brutefuzzy.proto', 'src/main/java' ] do
  sh "protoc --java_out=src/main/java proto/brutefuzzy.proto"
end

t.generated_files = [ messages_java ]

task :clean do
  rm_rf 'src'
end

file 'Manifest.txt' => [ 'pom.xml' ]

task :check_pom_version do
  t.test_line_match( 'pom.xml', /<version>/, /#{t.version}/ )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_version, :check_history_version                      ]
task :tag  => [ :check_pom_version, :check_history_version, :check_history_date ]
task :push => [                                             :check_history_date ]

t.define_tasks
