# -*- ruby -*-

FileList[ '_dot/*.dot' ].each do |dot|
  svg = dot.sub( /(\.dot)$/, '.svg' ).sub( /^(_dot)/, 'svg' )

  file svg => [ dot ] do
    sh "dot -Tsvg -o #{svg} #{dot}"
  end

  task :default => svg
end
