# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-simhash/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-simhash',
                       Iudex::Simhash::VERSION,
                       :no_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps   += [ [ 'gravitext-util', '~> 1.5.0' ],
                      [ 'iudex-filter',   '~> 1.0.0' ],
                      [ 'iudex-html',     '~> 1.0.0' ] ]

  h.testlib = :minitest
  h.extra_dev_deps << [ 'minitest',       '~> 1.7.1' ]
end

file 'Manifest.txt' => [ 'pom.xml' ]

task :check_pom_version do
  t.test_line_match( 'pom.xml', /<version>/, /#{t.version}/ )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_version, :check_history_version                      ]
task :tag  => [ :check_pom_version, :check_history_version, :check_history_date ]
task :push => [                                             :check_history_date ]

t.define_tasks
