MANIFEST = FileList["Manifest.txt", "Rakefile", "README.txt", "LICENSE.txt", "lib/**/*"]

file "Manifest.txt" => :manifest
task :manifest do
  File.open("Manifest.txt", "w") {|f| MANIFEST.each {|n| f << "#{n}\n"} }
end
Rake::Task['manifest'].invoke # Always regen manifest, so Hoe has up-to-date list of files

ENV['NODOT'] = "no thank you"


$LOAD_PATH << "lib"
require "jdbc/postgres"
begin
  require 'hoe'
  Hoe.new("jdbc-postgres", Jdbc::Postgres::VERSION + ".0" ) do |p|
    p.rubyforge_name = "jruby-extras"
    p.author = "Nick Sieger, Ola Bini, David Kellum and JRuby contributors"
    p.email = "nick@nicksieger.com, ola.bini@gmail.com, dek-ruby@gravitext.com"
    p.summary = "PostgreSQL JDBC driver for Java and PostgreSQL/ActiveRecord-JDBC."
    p.changes = "Updated to PostgreSQL version #{Jdbc::Postgres::VERSION}-603 (JDBC 4)."
    p.description = "Install this gem and require 'postgres' within JRuby to load the driver."
  end.spec.dependencies.delete_if { |dep| dep.name == "hoe" }
rescue LoadError
  puts "You really need Hoe installed to be able to package this gem"
rescue => e
  puts "ignoring error while loading hoe: #{e.to_s}"
end
