destination: ./_site
exclude    : [ "Rakefile", "Gemfile", "Gemfile.lock" ]
auto:        false
lsi:         false
server_port: 4000
pygments:    true
markdown:    kramdown
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
