# -*- ruby -*-

source 'https://rubygems.org'

gem 'rake',              '>= 0.9.2.2', '< 13'
gem 'jekyll',            '~> 1.5.0'
gem 'liquid',            '~> 2.5.1'
gem 'kramdown',          '~> 1.2.0'
gem 'coderay',           '~> 1.0.9'
gem 'jekyll-svg-plugin', '~> 1.1.0'
