# -*- ruby -*-

source :rubygems

gem 'rake',              '~> 10.0.3'
gem 'jekyll',            '~> 0.11.2'
gem 'liquid',            '~> 2.3.0'
gem 'directory_watcher', '~> 1.4.1'
gem 'kramdown',          '~> 0.13.7'
gem 'coderay',           '~> 1.0.7'
gem 'jekyll-svg-plugin', '~> 1.1.0'
