# -*- ruby -*-
source :rubygems

gem 'rake',              '~> 0.9.2'
gem 'jekyll',            '~> 0.11.2'
gem 'kramdown',          '~> 0.13.3'
gem 'liquid',            '~> 2.3.0'
gem 'directory_watcher', '~> 1.4.1'
gem 'minitest',          '~> 2.3'
gem 'jekyll-svg-plugin', '~> 1.1.0'
