# -*- ruby -*-

task :default => [ :gen ]

directory 'svg'

FileList[ '_dot/*.dot' ].each do |dot|
  svg = dot.sub( /(\.dot)$/, '.svg' ).sub( /^(_dot)/, 'svg' )
  png = dot.sub( /(\.dot)$/, '.png' ).sub( /^(_dot)/, 'svg' )

  file svg => [ dot, 'svg' ] do
    sh "dot -Tsvg -o #{svg} #{dot}"
  end

  file png => [ dot, 'svg' ] do
    sh "dot -Tpng -o #{png} #{dot}"
  end

  task :dot => [ svg, png ]
end

task :clean do
  rm_rf %w[ svg _site ]
end

task :gen => [ :dot ] do
  sh "bundle exec jekyll"
end

task :server => [ :dot ] do
  sh "bundle exec jekyll --auto --server"
end

DEST="/home/david/public_html/iudex"

task :diff => [ :gen ]  do
  sh "rsync -n -rc -i _site/ #{DEST}"
end

task :publish => [ :gen ] do
  sh "rsync -rc -i _site/ #{DEST}"
end
