# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'

task :default => [ :gen ]

directory 'svg'

FileList[ '_dot/*.dot' ].each do |dot|
  svg = dot.sub( /(\.dot)$/, '.svg' ).sub( /^(_dot)/, 'svg' )
  png = dot.sub( /(\.dot)$/, '.png' ).sub( /^(_dot)/, 'svg' )

  file svg => [ dot, 'svg' ] do
    sh "dot -Tsvg -o #{svg} #{dot}"
  end

  file png => [ dot, 'svg' ] do
    sh "dot -Tpng -o #{png} #{dot}"
  end

  task :dot => [ svg, png ]
end

task :clean do
  rm_rf %w[ svg _site ]
end

desc "Run Jekyll to generate files"
task :gen => [ :dot ] do
  require 'jekyll'
  ARGV.replace( %w[ build ] )
  load Gem.bin_path( 'jekyll', 'jekyll' )
end

desc "Run auto-regenerating Jekyll server"
task :server => [ :dot ] do
  require 'jekyll'
  ARGV.replace( %w[ serve --watch ] )
  load Gem.bin_path( 'jekyll', 'jekyll' )
end

desc "Upload to Amazon S3 (gravitext.com, Oregon)"
task :publish => [ :gen ] do
  sh "s3cmd -P -M sync --exclude '*.css' _site/ s3://iudex.gravitext.com/"
  sh "s3cmd -P -m text/css sync _site/css/ s3://iudex.gravitext.com/css/"
end
