# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-http-test/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.4'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-http-test',
                       Iudex::HTTP::Test::VERSION,
                       :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )
  h.extra_deps += [ [ 'fishwife', '~> 1.1.0' ],
                    [ 'sinatra',  '>= 1.2.6', '< 1.4' ],
                    [ 'markaby',  '~> 0.7.1' ],
                    [ 'minitest', '~> 2.3' ] ]

  h.testlib = :minitest
  h.extra_dev_deps += [ [ 'rack-test',  '~> 0.6.0' ] ]
end

task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_history_version                      ]
task :tag  => [ :check_history_version, :check_history_date ]
task :push => [                         :check_history_date ]

t.define_tasks
