# -*- ruby -*-

require 'rubygems'
require 'bundler/setup'
require 'rjack-tarpit'

RJack::TarPit.new( 'iudex-html' ).define_tasks

file 'target/.tarpit' => [ 'src/main/java/iudex/html/HTML.java' ]

file 'src/main/java/iudex/html/HTML.java' => FileList.new( "build/*" ) do
  require_relative 'build/java_generate'
  puts "Generating HTML.java"
  JavaGenerator.new.run
end

task :clean do
  rm_f 'src/main/java/iudex/html/HTML.java'
end
