# -*- ruby -*-
source :rubygems
gemspec :path => '.', :name => 'iudex-async-httpclient'

RJack::TarPit.last_spec.dependencies.each do |d|
  gem( d.name, :path => "../#{d.name}" ) if d.name =~ /^iudex/
end
