# -*- ruby -*-

$LOAD_PATH << './lib'
require 'iudex-async-httpclient/base'

require 'rubygems'
gem     'rjack-tarpit', '~> 1.2'
require 'rjack-tarpit'

t = RJack::TarPit.new( 'iudex-async-httpclient',
                       Iudex::AsyncHTTPClient::VERSION,
                       :no_assembly, :java_platform )

t.specify do |h|
  h.developer( "David Kellum", "dek-oss@gravitext.com" )

  h.extra_deps += [ [ 'iudex-http',             '~> 1.1.0' ],
                    [ 'rjack-async-httpclient', '~> 1.6.5' ],
                    [ 'hooker',                 '~> 1.0.0' ] ]

  h.testlib = :minitest
  h.extra_dev_deps += [ [ 'minitest',        '~> 2.3' ],
                        [ 'iudex-http-test', '~> 1.0.0' ],
                        [ 'rjack-logback',   '~> 1.0' ] ]
end

file 'Manifest.txt' => "lib/#{t.name}/base.rb"

task :check_pom_version do
  t.test_line_match( 'pom.xml', /<version>/, /#{t.version}/ )
end
task :check_history_version do
  t.test_line_match( 'History.rdoc', /^==/, / #{t.version} / )
end
task :check_history_date do
  t.test_line_match( 'History.rdoc', /^==/, /\([0-9\-]+\)$/ )
end

task :gem  => [ :check_pom_version, :check_history_version                      ]
task :tag  => [ :check_pom_version, :check_history_version, :check_history_date ]
task :push => [                                             :check_history_date ]

t.define_tasks
